<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestoreConfigFile>$(XNodeSource)\eng\survival-beta.NuGet.Config</RestoreConfigFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(XNodeSource)\src\XNode.Core\XNode.Core.csproj" />
  </ItemGroup>
</Project>
