server {
  listen 80;
  listen [::]:80;
  server_name push.xpoint.network;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name push.xpoint.network;
  client_max_body_size 1m;

  ssl_certificate /etc/letsencrypt/live/registry.xpoint.network/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/registry.xpoint.network/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

  location = /subscribe {
    proxy_pass http://127.0.0.1:19102;
    include proxy_params;
  }

  location = /unsubscribe {
    proxy_pass http://127.0.0.1:19102;
    include proxy_params;
  }

  location = /_compat/push-notify {
    proxy_pass http://127.0.0.1:19102;
    include proxy_params;
  }

  location = /health/live {
    proxy_pass http://127.0.0.1:19102;
    include proxy_params;
  }

  location = /health/ready {
    proxy_pass http://127.0.0.1:19102;
    include proxy_params;
  }

  location / {
    return 404;
  }
}
