import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const compose = fs.readFileSync(path.join(root, 'docker-compose.survival-uat-tls.dev.yml'), 'utf8');
const standardUatCompose = fs.readFileSync(path.join(root, 'docker-compose.uat.yml'), 'utf8');
const privateUatCompose = fs.readFileSync(path.join(root, 'docker-compose.uat-private.yml'), 'utf8');
const productionCompose = fs.readFileSync(path.join(root, 'docker-compose.client-services.prod.yml'), 'utf8');
const proxy = fs.readFileSync(path.join(root, 'config', 'survival-uat-tls', 'haproxy.cfg'), 'utf8');
const fixture = fs.readFileSync(path.join(root, 'tools', 'membership-fixture', 'Program.cs'), 'utf8');
const bootstrap = fs.readFileSync(path.join(root, 'scripts', 'Initialize-SurvivalUatTls.ps1'), 'utf8');
const turnEntrypoint = fs.readFileSync(path.join(root, 'scripts', 'coturn-entrypoint.sh'), 'utf8');
const turnConfig = fs.readFileSync(path.join(root, 'config', 'coturn', 'turnserver.conf'), 'utf8');
const restartSmoke = fs.readFileSync(path.join(root, 'scripts', 'backend-external-restart-smoke.mjs'), 'utf8');

for (const service of ['xnode-1','xnode-2','xnode-3','xnode-4','xnode-5','xnode-6','registry','storage','file','push']) {
  assert.ok(compose.includes(`${service}: { ports: !reset [] }`), `${service} must not publish cleartext`);
}
assert.doesNotMatch(compose, /^  calls:/m);
assert.match(compose, /^  turn:/m);
assert.match(compose, /coturn\/coturn:4\.12\.0-alpine@sha256:[0-9a-f]{64}/);
assert.match(compose, /cap_drop: \[ALL\][\s\S]*?cap_add: \[NET_BIND_SERVICE\]/);
assert.match(compose, /3478:3478\/udp/);
assert.match(compose, /5349:5349\/tcp/);
assert.match(compose, /49160-49200:49160-49200\/udp/);
assert.match(compose, /DEEP_TURN_SHARED_SECRET_FILE: \/run\/secrets\/turn-shared-secret/);
assert.match(compose, /turn-shared-secret:\s*\r?\n\s+file: \$\{SURVIVAL_UAT_TLS_SECRET_DIR/);
assert.doesNotMatch(compose, /static-auth-secret=/);
assert.doesNotMatch(standardUatCompose, /^  calls:/m);
assert.doesNotMatch(standardUatCompose, /calls-state|docker\/calls-service\.Dockerfile/);
assert.match(standardUatCompose, /Calls__StatePath: \/var\/lib\/deep\/registry\/calls-v2\.json/);
assert.match(standardUatCompose, /"28103:8080"/);
assert.match(standardUatCompose, /^  turn:/m);
assert.doesNotMatch(standardUatCompose, /static-auth-secret=/);
assert.doesNotMatch(privateUatCompose, /^  calls:/m);
assert.doesNotMatch(privateUatCompose, /calls-state|docker\/calls-service\.Dockerfile/);
assert.match(productionCompose, /DEEP_TURN_SHARED_SECRET_FILE: \/run\/secrets\/turn-shared-secret/);
assert.doesNotMatch(productionCompose, /static-auth-secret=/);
assert.match(productionCompose, /entrypoint: \["\/usr\/local\/bin\/deep-coturn-entrypoint"\]/);
assert.match(compose, /haproxy:3\.2\.22-alpine3\.24@sha256:79799e8b2977e60802774fa53d29e6b54e045402cdd8a8b9fe43923e7095a047/);
assert.match(compose, /SURVIVAL_UAT_TLS_SECRET_DIR:\?set SURVIVAL_UAT_TLS_SECRET_DIR/);
assert.doesNotMatch(compose, /41820:41820/);
assert.match(compose, /41824:8080/);
assert.match(compose, /\/public:ro/);
assert.match(compose, /--advertised-scheme, https/);
assert.match(compose, /DEEP_UAT_XNODE_1_UPSTREAM: xnode-1:8082/);
assert.match(compose, /DEEP_UAT_XNODE_3_UPSTREAM: xnode-3:8082/);
assert.match(proxy, /ssl-min-ver TLSv1\.2 no-tls-tickets/);
assert.doesNotMatch(proxy, /verify none|ca-ignore-err|ssl_c_verify/);
assert.match(proxy, /deny_status 404/);
assert.match(proxy, /http-request del-header Forwarded/);
assert.match(proxy, /http-request del-header X-Forwarded-Proto/);
assert.equal((proxy.match(/http-request set-header X-Forwarded-Proto https if post public_post/g) ?? []).length, 6);
assert.match(proxy, /req\.hdr\(content-length\).*33554432/);
assert.equal((proxy.match(/acl public_post path \/api\/ingress\/v1\/frame/g) ?? []).length, 6);
assert.equal((proxy.match(/\/api\/network\/privacy-contact/g) ?? []).length, 6);
assert.doesNotMatch(proxy, /api\/session\/rpc|api\/peer\/onion|api\/network\/contact/);
assert.match(proxy, /server xnode-1 "\$DEEP_UAT_XNODE_1_UPSTREAM" proto h2 check/);
assert.match(proxy, /server xnode-3 "\$DEEP_UAT_XNODE_3_UPSTREAM" proto h2 check/);
assert.equal((proxy.match(/server xnode-[1-6] [^\r\n]+ proto h2 check/g) ?? []).length, 6);
assert.equal((proxy.match(/http-response del-header Date/g) ?? []).length, 6);
assert.equal((proxy.match(/http-response del-header Server/g) ?? []).length, 6);
assert.equal((proxy.match(/http-response set-header Cache-Control no-store/g) ?? []).length, 6);
assert.match(proxy, /nameserver docker_dns 127\.0\.0\.11:53/);
assert.equal((proxy.match(/resolvers docker resolve-prefer ipv4 init-addr libc,none/g) ?? []).length, 15);
assert.equal((proxy.match(/use_backend xnode_[1-6]_metadata_backend if get public_get/g) ?? []).length, 6);
assert.equal((proxy.match(/server xnode-[1-6]-metadata xnode-[1-6]:8080 check/g) ?? []).length, 6);
assert.match(proxy, /acl ice path_beg \/api\/calls\/ice-servers\//);
assert.match(proxy, /frontend calls_public[\s\S]*?default_backend registry_backend/);
assert.doesNotMatch(proxy, /backend calls_backend|server calls /);
assert.match(fixture, /advertisedScheme\}:\/\//);
assert.match(bootstrap, /subjectAltName=IP:\$LanHost/);
assert.match(bootstrap, /basicConstraints=critical,CA:TRUE,pathlen:0/);
assert.match(bootstrap, /verify_ip/);
assert.match(bootstrap, /crlDistributionPoints=URI:http:\/\/\$\{LanHost\}:41824/);
assert.doesNotMatch(bootstrap, /InstallWindowsCurrentUserRoot/);
assert.doesNotMatch(bootstrap, /expected-pin|SPKI|DangerousAcceptAny/);
assert.match(bootstrap, /turn-shared-secret/);
assert.match(turnEntrypoint, /static-auth-secret=\$secret/);
assert.match(turnEntrypoint, /exec turnserver -c "\$runtime_config"/);
assert.doesNotMatch(turnEntrypoint, /turnserver[^\n]*static-auth-secret/);
assert.doesNotMatch(turnConfig, /realm=|server-name=|static-auth-secret=|registry\.xpoint\.network/);
assert.doesNotMatch(restartSmoke, /calls-service|DEEP_CALL_STATS|urls\.calls/);
assert.match(restartSmoke, /deep-call-signal-v2/);
assert.match(restartSmoke, /deep-call-inbox-v2/);
assert.match(restartSmoke, /authenticatedInboxRetrievedAfterRestart/);
assert.match(restartSmoke, /'restart', 'storage-service', 'file-service', 'push-service', 'registry'/);

console.log('survival UAT TLS contracts passed');
